
package xmlRpcService;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebServiceClient(name = "ProductosXMLRPC", targetNamespace = "http://webServices/", wsdlLocation = "http://localhost:8080/xml/ProductosXMLRPC?wsdl")
public class ProductosXMLRPC_Service
        extends Service {

    private final static URL PRODUCTOSXMLRPC_WSDL_LOCATION;
    private final static WebServiceException PRODUCTOSXMLRPC_EXCEPTION;
    private final static QName PRODUCTOSXMLRPC_QNAME = new QName("http://webServices/", "ProductosXMLRPC");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/xml/ProductosXMLRPC?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTOSXMLRPC_WSDL_LOCATION = url;
        PRODUCTOSXMLRPC_EXCEPTION = e;
    }

    public ProductosXMLRPC_Service() {
        super(__getWsdlLocation(), PRODUCTOSXMLRPC_QNAME);
    }

    public ProductosXMLRPC_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTOSXMLRPC_QNAME, features);
    }

    public ProductosXMLRPC_Service(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTOSXMLRPC_QNAME);
    }

    public ProductosXMLRPC_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTOSXMLRPC_QNAME, features);
    }

    public ProductosXMLRPC_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductosXMLRPC_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTOSXMLRPC_EXCEPTION != null) {
            throw PRODUCTOSXMLRPC_EXCEPTION;
        }
        return PRODUCTOSXMLRPC_WSDL_LOCATION;
    }

    /**
     * @return returns ProductosXMLRPC
     */
    @WebEndpoint(name = "ProductosXMLRPCPort")
    public ProductosXMLRPC getProductosXMLRPCPort() {
        return super.getPort(new QName("http://webServices/", "ProductosXMLRPCPort"), ProductosXMLRPC.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ProductosXMLRPC
     */
    @WebEndpoint(name = "ProductosXMLRPCPort")
    public ProductosXMLRPC getProductosXMLRPCPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webServices/", "ProductosXMLRPCPort"), ProductosXMLRPC.class, features);
    }

}
