
package xmlRpcService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebService(name = "ProductosXMLRPC", targetNamespace = "http://webServices/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface ProductosXMLRPC {


    /**
     * @param quantity
     * @param code
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/ProductosXMLRPC/orderProductRequest", output = "http://webServices/ProductosXMLRPC/orderProductResponse")
    public String orderProduct(
            @WebParam(name = "code", partName = "code")
            String code,
            @WebParam(name = "quantity", partName = "quantity")
            int quantity);

    /**
     * @return returns xmlRpcService.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/ProductosXMLRPC/listProductsRequest", output = "http://webServices/ProductosXMLRPC/listProductsResponse")
    public StringArray listProducts();

}
