
package soapService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VacacionesSOAP", targetNamespace = "http://webServices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VacacionesSOAP {


    /**
     * 
     * @param solicitud
     * @return
     *     returns soapService.RespuestaVacaciones
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "solicitar", targetNamespace = "http://webServices/", className = "soapService.Solicitar")
    @ResponseWrapper(localName = "solicitarResponse", targetNamespace = "http://webServices/", className = "soapService.SolicitarResponse")
    @Action(input = "http://webServices/VacacionesSOAP/solicitarRequest", output = "http://webServices/VacacionesSOAP/solicitarResponse")
    public RespuestaVacaciones solicitar(
        @WebParam(name = "solicitud", targetNamespace = "")
        SolicitudVacaciones solicitud);

}
